import { RateItem } from '../types/estimation';

export const DEFAULT_RATE_DATABASE: RateItem[] = [
  // 1. Substructure & Earthwork
  {
    itemCode: 'EW-001',
    itemName: 'Earthwork Excavation in Foundation Trenches',
    category: 'Substructure & Earthwork',
    unit: 'cum',
    materialRate: 0,
    labourRate: 180.0,
    equipmentRate: 140.0,
    totalRate: 320.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },
  {
    itemCode: 'EW-002',
    itemName: 'Plain Cement Concrete (PCC 1:4:8) in Foundation',
    category: 'Substructure & Earthwork',
    unit: 'cum',
    materialRate: 3650.0,
    labourRate: 650.0,
    equipmentRate: 200.0,
    totalRate: 4500.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },
  {
    itemCode: 'EW-003',
    itemName: 'Anti-Termite Treatment & Soil Compaction',
    category: 'Substructure & Earthwork',
    unit: 'sqm',
    materialRate: 45.0,
    labourRate: 25.0,
    equipmentRate: 10.0,
    totalRate: 80.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },

  // 2. RCC & Structural Framework
  {
    itemCode: 'RCC-001',
    itemName: 'Reinforced Cement Concrete (M25 Grade) in Footings, Beams & Slabs',
    category: 'RCC & Structural Framework',
    unit: 'cum',
    materialRate: 5200.0,
    labourRate: 950.0,
    equipmentRate: 350.0,
    totalRate: 6500.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },
  {
    itemCode: 'RCC-002',
    itemName: 'Thermo-Mechanically Treated (TMT Fe500D) Reinforcement Rebar',
    category: 'RCC & Structural Framework',
    unit: 'MT',
    materialRate: 56000.0,
    labourRate: 6500.0,
    equipmentRate: 1500.0,
    totalRate: 64000.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },
  {
    itemCode: 'RCC-003',
    itemName: 'Centering & Shuttering (Plywood / Steel Formwork)',
    category: 'RCC & Structural Framework',
    unit: 'sqm',
    materialRate: 160.0,
    labourRate: 240.0,
    equipmentRate: 40.0,
    totalRate: 440.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },

  // 3. Masonry & Superstructure
  {
    itemCode: 'MAS-001',
    itemName: 'Class 1 Red Clay Brickwork (1:6 Cement Mortar)',
    category: 'Masonry & Superstructure',
    unit: 'cum',
    materialRate: 3950.0,
    labourRate: 1100.0,
    equipmentRate: 150.0,
    totalRate: 5200.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },
  {
    itemCode: 'MAS-002',
    itemName: 'Autoclaved Aerated Concrete (AAC) Block Masonry (with Polymer Mortar)',
    category: 'Masonry & Superstructure',
    unit: 'cum',
    materialRate: 3400.0,
    labourRate: 850.0,
    equipmentRate: 100.0,
    totalRate: 4350.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },

  // 4. Waterproofing & Plastering
  {
    itemCode: 'FIN-001',
    itemName: 'Internal Cement Plastering 12mm (1:4 Cement Sand Mortar)',
    category: 'Waterproofing & Plastering',
    unit: 'sqm',
    materialRate: 85.0,
    labourRate: 115.0,
    equipmentRate: 15.0,
    totalRate: 215.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },
  {
    itemCode: 'FIN-002',
    itemName: 'External Sponge Finish Plaster 18mm with Waterproofing Admixture',
    category: 'Waterproofing & Plastering',
    unit: 'sqm',
    materialRate: 130.0,
    labourRate: 160.0,
    equipmentRate: 25.0,
    totalRate: 315.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },
  {
    itemCode: 'FIN-003',
    itemName: 'Terrace & Wet Area Polymer Membrane Waterproofing',
    category: 'Waterproofing & Plastering',
    unit: 'sqm',
    materialRate: 220.0,
    labourRate: 95.0,
    equipmentRate: 20.0,
    totalRate: 335.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },

  // 5. Flooring & Tiling
  {
    itemCode: 'FLR-001',
    itemName: 'Vitrified Double-Charged Tile Flooring (600x600mm / 800x800mm)',
    category: 'Flooring & Tiling',
    unit: 'sqm',
    materialRate: 680.0,
    labourRate: 220.0,
    equipmentRate: 30.0,
    totalRate: 930.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },
  {
    itemCode: 'FLR-002',
    itemName: 'Granite Flooring & Staircase Treads with Edge Moulding',
    category: 'Flooring & Tiling',
    unit: 'sqm',
    materialRate: 1350.0,
    labourRate: 420.0,
    equipmentRate: 60.0,
    totalRate: 1830.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },

  // 6. Doors & Windows
  {
    itemCode: 'OPN-001',
    itemName: 'Hardwood Frames with Laminated Flush Doors & Architectural Hardware',
    category: 'Doors & Windows',
    unit: 'sqm',
    materialRate: 2400.0,
    labourRate: 480.0,
    equipmentRate: 50.0,
    totalRate: 2930.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },
  {
    itemCode: 'OPN-002',
    itemName: 'Powder-Coated / UPVC Glazed Sliding Windows with Mosquito Mesh',
    category: 'Doors & Windows',
    unit: 'sqm',
    materialRate: 3200.0,
    labourRate: 380.0,
    equipmentRate: 70.0,
    totalRate: 3650.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },

  // 7. Plumbing & Sanitary
  {
    itemCode: 'MEP-P01',
    itemName: 'Internal CPVC Water Supply & PVC Soil Waste Drainage Pipelines',
    category: 'Plumbing & Sanitary',
    unit: 'sqft GFA',
    materialRate: 55.0,
    labourRate: 35.0,
    equipmentRate: 8.0,
    totalRate: 98.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },
  {
    itemCode: 'MEP-P02',
    itemName: 'Vitreous China Sanitary Fixtures & Chrome Plated Brass Fittings',
    category: 'Plumbing & Sanitary',
    unit: 'set',
    materialRate: 14500.0,
    labourRate: 2200.0,
    equipmentRate: 300.0,
    totalRate: 17000.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },

  // 8. Electrical Infrastructure
  {
    itemCode: 'MEP-E01',
    itemName: 'Concealed FRLS Copper Wiring, Modular Switches & Distribution Boards',
    category: 'Electrical Infrastructure',
    unit: 'sqft GFA',
    materialRate: 75.0,
    labourRate: 40.0,
    equipmentRate: 10.0,
    totalRate: 125.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },

  // 9. Painting & Surface Finishes
  {
    itemCode: 'PNT-001',
    itemName: 'Internal 2-Coat Putty, Primer & Premium Acrylic Emulsion Paint',
    category: 'Painting & Surface Finishes',
    unit: 'sqm',
    materialRate: 65.0,
    labourRate: 75.0,
    equipmentRate: 10.0,
    totalRate: 150.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },
  {
    itemCode: 'PNT-002',
    itemName: 'External 100% Acrylic Weather-Proof Exterior Emulsion Paint System',
    category: 'Painting & Surface Finishes',
    unit: 'sqm',
    materialRate: 85.0,
    labourRate: 80.0,
    equipmentRate: 15.0,
    totalRate: 180.0,
    location: 'National Baseline (NCR)',
    effectiveDate: '2026-01-01',
    source: 'Illustrative/MVP rate',
    status: 'Active',
  },
];
